name: Build and Publish DLLs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  trigger_submodule_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Submodule Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_PAT_PACK }}
          event-type: ${{ github.event.inputs.submodule_event_type }}
          client-payload: >
            {
              "workflow": "Build and Publish DLLs",
              "repository": "${{ github.repository }}",
              "repo_owner": "${{ github.repository_owner }}",
              "triggered_commit": "${{ github.sha }}",
              "commit_tag": "${{ github.ref_name }}",
              "token": "${{ secrets.GH_PAT_PACK }}"
            }
