name: Build and Publish DLLs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  run_dlls_builder:
    runs-on: windows-latest

    steps:
      - name: Use External Action
        uses: OSTOLEX-Technologies/DLL-builder-action@225d62e7ed53fc1e32bb3ce6377869ac1275f754
        with:
          token: ${{ secrets.GH_PAT_PACK }}
