name: Build and Publish DLLs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  run_dlls_builder:
    runs-on: windows-latest

    steps:
      - name: Use External Action
        uses: OSTOLEX-Technologies/DLL-builder-action@5a11c01ef20e95bad158aab4bf124ddc559a773c
        with:
          token: ${{ secrets.GH_PAT_PACK }}
