name: Build and Publish DLLs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  run_dlls_builder:
    runs-on: windows-latest

    steps:
      - name: Use External Action
        uses: OSTOLEX-Technologies/DLL-builder-action@ac523186490fb3ac95ce39d71e118c42fa9f79cf
        with:
          token: ${{ secrets.GH_PAT_PACK }}
