name: Build and Publish DLLs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  run_dlls_builder:
    runs-on: windows-latest

    steps:
      - name: Use External Action
        uses: OSTOLEX-Technologies/DLL-builder-action@f2bfd5ddc2856827c69db3e0fc7df456da00d4a5
        with:
          token: ${{ secrets.GH_PAT_PACK }}
