name: Build and Publish DLLs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  trigger_submodule_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Submodule Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: "build-dlls"
          client-payload: |-
            {
              "repository": "${{ github.repository }}",
              "repo_owner": "${{ github.repository_owner }}",
              "triggered_commit": "${{ github.sha }}",
              "commit_tag": "${{ github.ref_name }}"
            }
